### ISSUE TITLE
Robot enemigos se quedan inmóviles 

### ISSUE THREAD

**Issue by rodsan05** [Proyectos1-FDI-UCM/c2021-Grupo02#11]
% Errores encontrados: 8
% Rodrigo Sánchez Torres
% 24/05/2020

### Descripción

Los enemigos se quedan inmóviles si se sale al menú de inicio tras cambiar a heavy metal.

### Pasos 

1. Tener la música clásica activa.
2. Acercarse a uno o varios policías.
3. Cambiar la música a heavy.
4. Salir al menú de inicio.
5. Volver a entrar al juego.
6. Ir contra el mismo enemigo.
7. Se habrá quedado inmovilizado y no atacará.
8. Si se cambia a heavy otra vez, vuelve a moverse.

### Captura de pantalla o vídeo

Video: https://youtu.be/clJ408rgpew

**Comment by damart24** [comment]
Ya está arreglado
