### ISSUE TITLE
Enemigo huye permanentemente 

### ISSUE THREAD

**Issue by rodsan05** [Proyectos1-FDI-UCM/c2021-Grupo02#12]
% Errores encontrados: 8
% Rodrigo Sánchez Torres
% 24/05/2020

### Descripción

Si se cambia rápidamente de canción a música heavy y luego a electrónica, el enemigo empieza a huir permanentemente del jugador.

### Pasos 

1. Ir hacia un robot policía.
2. Cambiar a música heavy.
3. Cambiar rápidamente a música electrónica.
4. El enemigo se queda huyendo.

### Captura de pantalla o vídeo

Video: https://youtu.be/OK_ref0_Awc

**Comment by damart24** [comment]
Limitada capacidad de cambio de música y reducido el tiempo de retroceso, ya no huyen constantemente por ello
