### ISSUE TITLE
No se puede disparar en los pasillos

### ISSUE THREAD

**Issue by rodsan05** [Proyectos1-FDI-UCM/c2021-Grupo02#13]
% Errores encontrados: 8
% Rodrigo Sánchez Torres
% 24/05/2020

### Descripción

Si el jugador o un policía dispara en los pasillos la bala colisiona con los muros y se destruye instantáneamente.

### Pasos 

1. Caminar hasta un pasillo.
2. Quedarse en medio del pasillo.
3. Disparar.

### Captura de pantalla o vídeo

Video: https://youtu.be/f7VlVniPie4

**Comment by damart24** [comment]
No se debe poder disparar en los pasillos ya que ahí no hay enemigos y no deberían pasar, ya está arreglado que no entren ya que se les ha reducido el rango
