### ISSUE TITLE
Desaparición del disco al chocar con un proyectil del guardia

### ISSUE THREAD

**Issue by Sebana02** [Proyectos1-FDI-UCM/c2021-Grupo02#14]
% Errores encontrados: 7
% Sergio Baña Marchante 
% 24/05/2021

### Descripción

Al lanzar un disco con música clásica/electrónica (cuando los guardias disparan), si este choca con un proyectil de los guardias desaparece (el proyectil no desaparece). Se esperaba que desapareciera también el proyectil del enemigo.

### Pasos 

1. Poner la música clásica/electrónica
2. Dirigirse hacia la sala donde están los guardias de seguridad
3. Hacer que te disparen y disparar un disco hacia los proyectiles

### Captura de pantalla o vídeo

Video: https://youtu.be/RHS-H8zUdrs

**Comment by damart24** [comment]
Puesta layer para que no colisionen balas entre ellas
