### ISSUE TITLE
Desactivar panel de controles en el menú de escape 

### ISSUE THREAD

**Issue by Sebana02** [Proyectos1-FDI-UCM/c2021-Grupo02#15]
% Errores encontrados: 7
% Sergio Baña Marchante 
% 24/05/2021

### Descripción

Cuando se activa el menú de controles en el menú de pausa, se cierra el menú de pausa y se vuelve a abrir, sigue abierto el menú de controles, es decir, una vez abierto no se cierra. Se esperaba que se cerrase.

### Pasos 

1. Abrir el juego y presionar “escape” (abrir el menú de pausa)
2. Abrir el menú de controles
3.Cerrar el menú de pausa
4.Volver a abrir el menú de pausa

### Captura de pantalla o vídeo

Video: https://youtu.be/ZiprUoSU_PE

**Comment by damart24** [comment]
Ya se desactivan los paneles de controles/sonido al dar a escape de nuevo
