### ISSUE TITLE
 Error con el efecto de parálisis

### ISSUE THREAD

**Issue by JGomezPulido** [Proyectos1-FDI-UCM/c2021-Grupo02#16]
% Error con el efecto de parálisis
% José María Gómez Pulido
% 27/05/2021

### Descripción

Resultado esperado: Al paralizarme el robot policía, debería aparecer un efecto de rayos alrededor del jugador.
Resultado obtenido: Dicho efecto no aparece.

### Pasos 
1.  Recibir un disparo del robot policía mientras te mueves en cualquier dirección.

### Captura de pantalla o vídeo

https://youtu.be/VKGysmhQsOE

**Comment by damart24** [comment]
Error arreglado, añadidas las partículas
