### ISSUE TITLE
Error en el comportamiento del robot policía

### ISSUE THREAD

**Issue by Bimbloc** [Proyectos1-FDI-UCM/c2021-Grupo02#2]
%  Errores encontrados 4
%  Rocío Sánchez
%  21/05/2021
### Descripción
El robot policía **no sigue el patrón de comportamiento descrito en el documento**.Tras embestirte la primera vez no vuelve a moverse, se queda pegado al jugador el cual tampoco es capaz de moverse.La vida continúa bajando y eventualmente mueres y puedes volver al menú. 
### Pasos
1.  Cambié a la música heavy en el descansillo
1.  Entré a la  sala de la izquierda y bajé  hacia abajo
1.  Dejé que los enemigos me embistieran una  vez 
1.  Tras la embestida, el jugador se queda atascado en la pared
1.  Los guardias no se alejan de ti y no te puedes mover

He sido capaz de replicar este error.Al activar la música heavy y entrar en la sala de la izquierda muy cerca  de la pared es probable quedarse atascado tras la embestida.
Captura de pantalla o vídeo
![intento 2 21_05_2021 14_56_48](https://user-images.githubusercontent.com/82374311/119154313-528d2b00-ba52-11eb-8bac-40453b18ef47.png)
![intento 2 21_05_2021 14_57_05](https://user-images.githubusercontent.com/82374311/119154393-69338200-ba52-11eb-9547-8638a64555e0.png)
![intento 2 21_05_2021 14_56_48](https://user-images.githubusercontent.com/82374311/119154458-794b6180-ba52-11eb-89f4-f510c66adb69.png)

**Comment by nahigles** [comment]
He encontrado el mismo error y también hay veces que directamente no perciben y se quedan inmóviles sin atacarte. Aquí va el video:

![Video donde se ve el error] (https://youtu.be/3RQo88G8qFw)

**Comment by damart24** [comment]
Esa es la intención que se esquiven para que no te dejen atascado, pero además al cambiar de música los enemigos retroceden por si pasa esto para permitir al jugador huir de dichos enemigos.
