### ISSUE TITLE
Aparición espontánea de un guardia en la  sala de la izquierda

### ISSUE THREAD

**Issue by Bimbloc** [Proyectos1-FDI-UCM/c2021-Grupo02#3]
%  Errores encontrados 4
%   Rocio Sánchez
%    21/05/2021
### Descripción
Al salir de la sala de la izquierda encontré un enemigo de otra sala entrando 
### Pasos
1. Tenía la música electrónica puesta
1.   Siguiendo el documento cambié a la música heavy
1.  Cambié a la música clásica
1.   Uno de los  2 robots policías murió 
1.  Al salir de la sala había un guardia ya dentro de ella pero en frente del pasillo.

Fui capaz de replicar el error , la segunda vez el guardia se  encontraba en el lobby central(repitiendo exactamente los pasos detallados anteriormente)
Captura de pantalla o vídeo
![intento 2 21_05_2021 15_12_13 (1)](https://user-images.githubusercontent.com/82374311/119154909-ea8b1480-ba52-11eb-8297-2d36f382ae39.png)
![intento 2 21_05_2021 15_23_30](https://user-images.githubusercontent.com/82374311/119154943-f24ab900-ba52-11eb-8d34-cd2d4d690f09.png)

**Comment by jacall02** [comment]
Rango mal configurado de algunos de las instancias
