### ISSUE TITLE
Aparición espontánea de un Robot policía en la  sala de abajo

### ISSUE THREAD

**Issue by Bimbloc** [Proyectos1-FDI-UCM/c2021-Grupo02#4]
%   Errores encontrados 4
%  Rocio-Sanchez
%   21/05/2021
### Descripción
Al entrar en la sala de abajo donde  solo debería haber 3 guardias encontré un robot policía
### Pasos
1.Tenía la música heavy puesta
1. Entré en la sala de abajo
1. Esperé a que los  guardias me atacaran
1. Uno de los  robots policías apareció embistiendo por la esquina superior izquierda de la pantalla. 
Fui capaz de  replicar el error ,de hecho la segunda vez aparecieron los  2 robots policía(no me dio tiempo a capturarlo)
En el tercer intento el robot policía no llegó a la sala pero se quedó flotando en el limbo azul entre ellas.  
Captura de pantalla o vídeo
![intento 2 21_05_2021 15_31_42](https://user-images.githubusercontent.com/82374311/119155278-49e92480-ba53-11eb-9778-00ec71c38ec5.png)
![intento 2 21_05_2021 15_44_13](https://user-images.githubusercontent.com/82374311/119155286-4c4b7e80-ba53-11eb-98b1-cdbbd71e474a.png)

**Comment by jacall02** [comment]
Rango mal configurado de algunos de las instancias
