### ISSUE TITLE
Error disparo de discos seguido con música

### ISSUE THREAD

**Issue by nahigles** [Proyectos1-FDI-UCM/c2021-Grupo02#5]
% Errores encontrados: 11
% Nahia Iglesias Calvo
% 24/05/2021

### Descripción

Al tener la música clásica sonando, como va sumando 1 disco por segundo y hay que esperar 1 segundo para disparar el siguiente disco, no se pueden disparar 4 discos seguidos como indica el plan de pruebas. Para encontrar este error hay que clickar con el lado izquierdo del ratón 4 veces seguidas y se puede observar que no baja más del número 19.

### Pasos 

1. Ejecutar el juego
2. Moverse a la sala de la derecha
3. Tener activada la música clásica
4. Click izquierdo 4 veces seguidas

### Captura de pantalla o vídeo

![image](https://user-images.githubusercontent.com/82345386/119280642-99d21200-bc32-11eb-9a5a-5ea99b495af6.png)

**Comment by sarais02** [comment]
Es debido a la cadencia de los discos, si das clicks inmediatamente seguidos no disparará hasta que pase cierto tiempo. Además antes teníamos un error en el que si te movias no podias disparar, pero lo solucionamos cambiando el ordena de las instrucciones en el script de ControlesPlayer
