### ISSUE TITLE
Rayos de Robot Policía no inmoviliza mientras se pulsa WASD

### ISSUE THREAD

**Issue by nahigles** [Proyectos1-FDI-UCM/c2021-Grupo02#6]
% Errores encontrados: 11
% Nahia Iglesias Calvo
% 24/05/2021

### Descripción

Si el jugador no se está desplazando y no está pulsando WASD a partir del momento en el que le da el rayo, se queda inmovilizado. En cambio, si el rayo le da en movimiento sigue avanzando en línea recta hacia donde estaba yendo el jugador hasta que a los segundos se pasa el efecto. Para encontrar este error hay que dejarse disparar por el enemigo Robot Policía que está en la sala de la izquierda con la música clásica activada, primero sin mover al jugador y a continuación en movimiento.

### Pasos 

1. Tener activada la música clásica
2. Ir a la sala de la izquierda
3. Dejarte disparar por los Robot Policía estando quieto
4. Paso anterior pero en movimiento

### Captura de pantalla o vídeo

!(https://youtu.be/o70gPSU47tY)

**Comment by jacall02** [comment]
Mecánica intencionada
