### ISSUE TITLE
El jugador se atasca en el pasillo derecho

### ISSUE THREAD

**Issue by nahigles** [Proyectos1-FDI-UCM/c2021-Grupo02#8]
% Errores encontrados: 11
% Nahia Iglesias Calvo
% 24/05/2021

### Descripción

Yendo y viniendo a la sala de la derecha, si el jugador se queda pegado a la pared de arriba se atasca y no anda hasta que se separa. Para encontrar este error hay que pegarse a la pared y andar.

### Pasos 

1.	Ir al pasillo de la sala derecha
2.	Pegarse a la pared de arriba
3.	Andar hacia la derecha
4.	Ahora hacia la izquierda

### Captura de pantalla o vídeo

!(https://youtu.be/QZYfwGamuSE)

**Comment by damart24** [comment]
Collider mal colocado, no afecta en las escenas principales
