### ISSUE TITLE
Guardia de seguridad no hace daño cuerpo a cuerpo con música Heavy

### ISSUE THREAD

**Issue by nahigles** [Proyectos1-FDI-UCM/c2021-Grupo02#9]
% Errores encontrados: 11
% Nahia Iglesias Calvo
% 24/05/2021

### Descripción

Cuando el guardia está al lado del jugador y activa la animación de daño cuerpo a cuerpo (con la porra) no baja ninguna pila en la interfaz cuando tendría que bajar uno de daño. Para encontrar este error solo hay que activar la música Heavy y dejarse pegar por el guardia.

### Pasos 

1. Ir a la sala de abajo
2. Activar música Heavy con el número 2
3. Dejar que los guardias se acerquen
4. Dejarse pegar y mirar las pilas

### Captura de pantalla o vídeo

!(https://youtu.be/o70gPSU47tY)

**Comment by miriam-m-s** [comment]
Era un fallo de un policía duplicado que tenía dos scripts
